version: "{branch} #{build}"

shallow_clone: true

image:
    - Visual Studio 2017
    - Visual Studio 2015

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

build:
    parallel: true

environment:
    matrix:
        - generator: "Visual Studio 15 2017"
          select_sv: -DCMAKE_CXX_FLAGS:="-Dstring_view_CONFIG_SELECT_STRING_VIEW=string_view_STRING_VIEW_STD"
        - generator: "Visual Studio 15 2017"
          select_sv: -DCMAKE_CXX_FLAGS:="-Dstring_view_CONFIG_SELECT_STRING_VIEW=string_view_STRING_VIEW_NONSTD"
        - generator: "Visual Studio 14 2015"
        - generator: "Visual Studio 12 2013"
        - generator: "Visual Studio 11 2012"
        - generator: "Visual Studio 10 2010"
        - generator: "Visual Studio 9 2008"

matrix:
    exclude:
        - image:      Visual Studio 2015
          generator: "Visual Studio 15 2017"
        - image:      Visual Studio 2017
          generator: "Visual Studio 14 2015"
        - image:      Visual Studio 2017
          generator: "Visual Studio 12 2013"
        - image:      Visual Studio 2017
          generator: "Visual Studio 11 2012"
        - image:      Visual Studio 2017
          generator: "Visual Studio 10 2010"
        - image:      Visual Studio 2017
          generator: "Visual Studio 9 2008"
        - image:      Visual Studio 2015
          platform:   x64
          generator: "Visual Studio 9 2008"

before_build:
    - mkdir build && cd build
    - cmake -A %platform% -G "%generator%" "%select_sv%" -DCMAKE_CXX_FLAGS:="-Dstring_view_CONFIG_SELECT_STRING_VIEW=string_view_STRING_VIEW_NONSTD" -DSTRING_VIEW_LITE_OPT_BUILD_TESTS=ON -DSTRING_VIEW_LITE_OPT_BUILD_EXAMPLES=OFF ..

build_script:
    - cmake --build . --config %configuration%

test_script:
    - ctest --output-on-failure -C %configuration%
